<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\BaseController;
use Illuminate\Http\Request;
use App\Http\Models\Slider;
use Illuminate\Database\Eloquent\Model;

class SliderController extends BaseController
{
    public function __construct()
    {
        $this->model = Slider::class;
        $this->prefix = "admin.slider";
        $this->routePath="slider.index";
    }

    public function dataForIndex(): array
    {
        return array(
            'publish'=> Slider::get(),
        );
    }

    protected function validateFormBeforeSave(Request $request)
    {
        $this->validate($request, [
            'link'=>'required',
            // 'img'=>'required|mimes:jpeg,png,png',
        ]);
    }

    protected function validateFormBeforeUpdate(Request $request)
    {
        $this->validate($request, [
            'link'=>'required',
            // 'img'=>'required|mimes:jpeg,png,png',
        ]);
    }

    protected function beforeUpdate(Model $model, Request $request)
    {
        parent::beforeUpdate($model, $request); // TODO: Change the autogenerated stub
        if ($request->hasFile('img')) {
            try{
                $image = $request->file('img');
                $im = $image->store('slider', 'public');
                $this->data['img']=$im;
            }catch (\Exception $ex){

            }
        }
    }

    protected function beforeSave(Request $request)
    {
        parent::beforeSave($request); // TODO: Change the autogenerated stub
        if ($request->hasFile('img')) {
            try{
                $image = $request->file('img');
                $im = $image->store('slider', 'public');
                $this->data['img']=$im;
            }catch (\Exception $ex){

            }
        }
    }
}
